// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj8w_sPQySJmEFBHUm4qhb-yAUrlMtOEE',
    appId: '1:433279035778:web:1ae358a7072e5b3725479b',
    messagingSenderId: '433279035778',
    projectId: 'hortiprice-2431a',
    authDomain: 'hortiprice-2431a.firebaseapp.com',
    storageBucket: 'hortiprice-2431a.firebasestorage.app',
    measurementId: 'G-FCCCCKD2QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvS5uGdbSpg9QnclxXEkjlESK4txUoIh4',
    appId: '1:433279035778:android:e81165906751ef4d25479b',
    messagingSenderId: '433279035778',
    projectId: 'hortiprice-2431a',
    storageBucket: 'hortiprice-2431a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-EETScPedko8ubuaQM8w5kUBX2v4qwyw',
    appId: '1:433279035778:ios:b91563822128a79025479b',
    messagingSenderId: '433279035778',
    projectId: 'hortiprice-2431a',
    storageBucket: 'hortiprice-2431a.firebasestorage.app',
    iosBundleId: 'com.example.hortiprice',
  );

}